- name: "Deploy upstream mig operator using OLM"
  block:

    - name: "Include required vars"
      include_vars:  "{{ lookup('first_found', olm_files) }}"
      vars:
        olm_files:
          - "{{ playbook_dir }}/olm/olm_vars.yml"
          - "{{ playbook_dir }}/roles/mig_controller_deploy/defaults/olm_vars.yml"

    - debug:
        msg:
          - "OLM cluster version: {{ olm_cluster_version }}"

    - name: "Create OperatorSource"
      k8s:
        state: present
        definition: "{{ lookup('file', '{{ mig_operator_location }}/mig-operator-source.yaml' )}}"
      register: mig_operator_source_created
      until: mig_operator_source_created is succeeded
      retries: 30
      delay: 30

    - name: "Define OperatorSource pod label"
      set_fact:
        mig_operator_label: "{{ 'marketplace.catalogSourceConfig=migration-operator' if olm_cluster_version is version('4.1', '<=') else 'marketplace.operatorSource=migration-operator' }}"

    - name: "Wait for OLM to reconcile OperatorSource creation"
      k8s_facts:
        kind: Pod
        namespace: openshift-marketplace
        label_selectors: "{{ mig_operator_label }}"
      register: pod
      until: pod.get("resources", []) | length > 0 and true in (pod | json_query('resources[].status.containerStatuses[].ready'))
      retries: 18
      delay: 10

    - name: "Confirm OperatorSource service availability"
      k8s_facts:
        kind: Service
        namespace: openshift-marketplace
        name: migration-operator
      register: service
      until: "'grpc' in (service | json_query('resources[].spec.ports[].name'))"
      retries: 18
      delay: 10

    - name: "Create {{ mig_migration_namespace }} namespace"
      k8s:
        name: "{{ mig_migration_namespace }}"
        kind: Namespace
        state: present
        wait: yes

    - name: "Create OperatorGroup"
      k8s:
        state: present
        definition: "{{ lookup('template', 'mig-operator-operatorgroup.yml.j2' ) }}"

    - name: "Create Subscription"
      k8s:
        state: present
        definition: "{{ lookup('template', 'mig-operator-subscription.yml.j2' ) }}"
