- name: "Deploy downstream mig operator using OLM"
  block:

    - name: "Create {{ mig_migration_namespace }} namespace"
      k8s:
        name: "{{ mig_migration_namespace }}"
        kind: Namespace
        state: present

    - name: "Create OperatorGroup"
      k8s:
        state: present
        definition: "{{ lookup('template', 'mig-operator-operatorgroup.yml.j2' ) }}"

    - name: "Create operator subscription"
      k8s:
        state: present
        definition: "{{ lookup('template', 'mig-operator-subscription.yml.j2' ) }}"
