---

- name: "Extract kubernetes minor version from cluster_info"
  set_fact:
    k8s_minor_version: "{{ lookup('k8s', cluster_info='version').kubernetes.minor|replace('+', '') }}"

- name: "Map kubernetes minor to ocp releases"
  set_fact:
    cluster_version: >-
      "{{ '3.7' if k8s_minor_version is version('7', '<=') else
      '3.9' if k8s_minor_version is version('9', '=') else
      '3.10' if k8s_minor_version is version('10', '=') else
      '3.11' if k8s_minor_version is version('11', '=') else
      '4.1' if k8s_minor_version is version('13', '=') else
      '4.2' if k8s_minor_version is version('14', '=') else
      '4.3' if k8s_minor_version is version('16', '=') else
      '4.4' if k8s_minor_version is version('17', '>=') }}"

- set_fact:
    cluster_version: "{{ cluster_version|replace('\"', '') }}"

- block:

    - name: "Extract cluster API URL"
      shell: "{{ oc_binary }} whoami --show-server"
      register: api_url

    - debug:
        msg: "OCP cluster API: {{ api_url.stdout }}"

  when: show_cluster_api|bool

- debug:
    msg: "OCP cluster version: {{ cluster_version }}"
