---
- name: Get defaults
  include_vars:
    file: "{{ playbook_dir }}/config/ocp4/defaults.yml"
    
- include_vars:
    file: "{{ playbook_dir }}/config/velero_aws_creds.yml"

- name: Apply velero common prereqs
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('file', '{{ playbook_dir }}/velero/config/common/00-prereqs.yaml')}}"

- name: Create aws backupstoragelocation for velero
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', '05-ark-aws-backupstoragelocation.yaml.j2') | from_yaml }}"

- name: Create aws volumesnapshotlocation for velero
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', '06-ark-aws-volumesnapshotlocation.yaml.j2') | from_yaml }}"

- name: Create aws bucket cloud creds
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: cloud-credentials
        namespace: velero
      data:
        cloud: "{{ lookup('template', 'cloud-credentials.j2') | b64encode }}"

- name: Create velero deployment
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('file', '{{ playbook_dir }}/velero/config/minio/20-deployment.yaml')}}"
    
- name: Create restic daemonset
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('file', '{{ playbook_dir }}/velero/config/minio/30-restic-daemonset.yaml')}}"

- name: Fix restic pod dir mount for oc cluster up install
  shell: "oc set volume -n velero ds/restic --add --name=host-pods --path /tmp/openshift.local.clusterup/openshift.local.volumes/pods --overwrite"
  when: cluster_version == '3'
