- debug:
    msg: "Mig controller will deploy using release: {{ mig_operator_release }}"
    
- name: Deploy mig controller
  k8s:
    state: present
    definition: "{{ lookup('template', 'controller.yml.j2') }}"

- include: check.yml
